; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sun Sep 06 2020 03:22:32 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0

